//
// Created by ivanbrekman on 04.10.2021.
//

#ifndef SIMPLEPROCESSOR_CONFIG_H
#define SIMPLEPROCESSOR_CONFIG_H

#define VALIDATE_LEVEL 1
#define MAX_FILEPATH_SIZE 50

#endif //SIMPLEPROCESSOR_CONFIG_H
