//
// Created by ivanbrekman on 25.10.2021.
//

COND_JUMP_DEFINITION(jg,  13, >)
COND_JUMP_DEFINITION(jl,  14, <)
COND_JUMP_DEFINITION(je,  15, ==)
COND_JUMP_DEFINITION(jne, 16, !=)
COND_JUMP_DEFINITION(jge, 17, >=)
COND_JUMP_DEFINITION(jle, 18, <=)
